[build]
  publish = "dist"
  command = "npm run generate"

[[redirects]]
  from = "/docs"
  to = "/getting-started"

[[redirects]]
  from = "/new"
  to = "https://codesandbox.io/s/abell-playground-wcdq2"

[[redirects]]
  from = "/tutorial/create-portfolio"
  to = "/tutorial/"