const fs = require('fs');
const fetch = require('node-fetch');
const path = require('path');


async function beforeBuild(programInfo, { createContent }) {
  const changelogMD = await fetch('https://raw.githubusercontent.com/abelljs/abell/main/CHANGELOG.md')
    .then(res => res.text());

  const fixBracketsChangelog = changelogMD.replace(/{{/g, '\\{{');

  const changelog = {
    slug: 'changelog',
    title: "Changelog",
    createdAt: new Date(),
    description: "Includes the details of changes made in Abell.",
    isAutoGenerated: true,
    pageNum: 6,
    content: fixBracketsChangelog,
  }

  createContent(changelog);
  
  const contributingMD = await fetch('https://raw.githubusercontent.com/abelljs/abell/main/CONTRIBUTING.md')
    .then(res => res.text());

  const fixBracketsContributing = contributingMD.replace(/{{/g, '\\{{').replace(/\n\n\n/g, '<br/><br/>');

  const contributing = {
    slug: 'contributing',
    title: "Contributing to Abell",
    createdAt: new Date(),
    description: "A guide to contributing to Abell. Includes details about locally setting up the repository, making changes, and creating a PR.",
    isAutoGenerated: true,
    pageNum: 8,
    content: fixBracketsContributing,
  }
  
  createContent(contributing);
}


module.exports = { beforeBuild }