const fetch = require('node-fetch');


async function beforeBuild(programInfo, { createContent }) {
  console.log('...Fetching CHANGELOG');
  const changelogMD = await fetch('https://raw.githubusercontent.com/abelljs/abell/main/CHANGELOG.md')
    .then(res => res.text());

  const fixBracketsChangelog = changelogMD.replace(/{{/g, '\\{{');

  const changelog = {
    slug: 'changelog',
    title: "Changelog",
    createdAt: new Date(),
    description: "Includes the details of changes made in Abell.",
    isAutoGenerated: true,
    pageNum: 6,
    content: fixBracketsChangelog,
  }

  createContent(changelog);
}


module.exports = { beforeBuild }